server:
  port: 8080   # you can change this if needed (e.g., 8081)

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update              # creates/updates tables automatically (good for dev)
    show-sql: true                  # logs SQL queries in console
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Environment-specific Plaid configuration
plaid:
  client-id: ${PLAID_CLIENT_ID}
  secret: ${PLAID_SECRET}
  env: sandbox                      # or 'development' / 'production'
  # webhook-url: https://yourdomain.com/webhook

aws:
  access-key: ${S3_KEY}
  secret-key: ${S3_SECRET}
  region: us-east-2
  s3:
    bucket: ${S3_BUCKET}

